### ISSUE TITLE
Git repo initialisation error

### ISSUE THREAD

**Issue by JoeHitchen** [JoeHitchen/Outpost#8]
On the first run in a fresh set up, the following error seems to be raised occasionally:

```
txrx.transfer_git_history raised unexpected: IsADirectoryError(21, 'Is a directory')
Traceback (most recent call last):
  File "/usr/src/app/txrx.py", line 83, in _transfer_git_history
    repo = git.Repo(repo_path)
  File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 147, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /var/git/target.git

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/txrx.py", line 93, in _transfer_git_history
    shutil.copy2(os.path.join(os.environ.get('TERRAFORM_TEMPLATE_PATH'), file), repo_path)
  File "/usr/local/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/src/terraform/.terraform'
```

**Comment by JoeHitchen** [comment]
On analysis, the first error is expected, but the second is not. The second error is being caused by attempting to copy the `.terraform` directory using a utility `shutil.copy2` that only supports copying files. This raises two things which should be resolved:

- [x] A recursive copy should be used, to correctly handle directories in the target application
- [x] The `.terraform` directory should be explicitly excluded from the copy
